// <auto-generated />
using System;
using GameQuest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GameQuest.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GameQuest.Data.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MainCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MainCategoryId");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("775ae8ee-b03c-40e6-a3eb-af9b1d7a969a"),
                            Created = new DateTime(2021, 4, 2, 14, 23, 7, 272, DateTimeKind.Local).AddTicks(5924),
                            MainCategoryId = new Guid("0dd64c02-7aa0-467a-b71c-778cc082e514"),
                            SubCategoryId = new Guid("e7bc4f99-8b04-4fdd-94b3-1ee74d0d4994")
                        },
                        new
                        {
                            Id = new Guid("02692608-3db2-45de-9c11-e394f3d13b20"),
                            Created = new DateTime(2021, 4, 2, 14, 23, 7, 272, DateTimeKind.Local).AddTicks(7101),
                            MainCategoryId = new Guid("4f6c9c44-d2bf-43af-a372-aff15e48ae28"),
                            SubCategoryId = new Guid("e7bc4f99-8b04-4fdd-94b3-1ee74d0d4994")
                        },
                        new
                        {
                            Id = new Guid("951772f3-566d-402b-b100-af86c9d13c9d"),
                            Created = new DateTime(2021, 4, 2, 14, 23, 7, 272, DateTimeKind.Local).AddTicks(7113),
                            MainCategoryId = new Guid("2dfd820a-4260-44ec-95c2-f87576a31294"),
                            SubCategoryId = new Guid("e7bc4f99-8b04-4fdd-94b3-1ee74d0d4994")
                        },
                        new
                        {
                            Id = new Guid("dbb9b3fc-904a-4dad-857f-6fbb6e5b5048"),
                            Created = new DateTime(2021, 4, 2, 14, 23, 7, 272, DateTimeKind.Local).AddTicks(7116),
                            MainCategoryId = new Guid("8046fd8e-2643-4f66-9a01-c95ad87fc75e"),
                            SubCategoryId = new Guid("e7bc4f99-8b04-4fdd-94b3-1ee74d0d4994")
                        },
                        new
                        {
                            Id = new Guid("9939c4c8-89fa-45bd-a443-f6c7ee69a1e8"),
                            Created = new DateTime(2021, 4, 2, 14, 23, 7, 272, DateTimeKind.Local).AddTicks(7120),
                            MainCategoryId = new Guid("0dd64c02-7aa0-467a-b71c-778cc082e514"),
                            SubCategoryId = new Guid("1d5ad12d-d31d-489c-95cd-cf3e016b782d")
                        },
                        new
                        {
                            Id = new Guid("bc7522ae-2d1e-44c3-aebc-12ed30b93517"),
                            Created = new DateTime(2021, 4, 2, 14, 23, 7, 272, DateTimeKind.Local).AddTicks(7127),
                            MainCategoryId = new Guid("4f6c9c44-d2bf-43af-a372-aff15e48ae28"),
                            SubCategoryId = new Guid("1d5ad12d-d31d-489c-95cd-cf3e016b782d")
                        },
                        new
                        {
                            Id = new Guid("df7cfae7-8317-49a8-8fda-b46b12e9ef6d"),
                            Created = new DateTime(2021, 4, 2, 14, 23, 7, 272, DateTimeKind.Local).AddTicks(7130),
                            MainCategoryId = new Guid("2dfd820a-4260-44ec-95c2-f87576a31294"),
                            SubCategoryId = new Guid("217c83c9-1531-40e5-abc9-a20cc9edfcf0")
                        },
                        new
                        {
                            Id = new Guid("e70d3a3a-b40f-46fd-ad63-81e79bdad8c6"),
                            Created = new DateTime(2021, 4, 2, 14, 23, 7, 272, DateTimeKind.Local).AddTicks(7133),
                            MainCategoryId = new Guid("8046fd8e-2643-4f66-9a01-c95ad87fc75e"),
                            SubCategoryId = new Guid("217c83c9-1531-40e5-abc9-a20cc9edfcf0")
                        });
                });

            modelBuilder.Entity("GameQuest.Data.Content", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsInMenu")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contents");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3612e955-433f-429d-939a-afe2dbd8d312"),
                            Body = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque cursus erat non congue efficitur. Nulla sollicitudin sit amet dolor sed vestibulum. Aenean laoreet, nibh ac hendrerit egestas, metus urna semper orci, nec aliquet urna tellus at nibh. Vivamus vel sapien eget libero cursus hendrerit sed at quam. Etiam nec turpis urna. Donec at lacus in nibh cursus ullamcorper eget vitae lorem. In congue consectetur purus vitae porta. Donec volutpat rhoncus nisl, et placerat tellus fringilla et.",
                            Created = new DateTime(2021, 4, 2, 14, 23, 7, 272, DateTimeKind.Local).AddTicks(8430),
                            ImageUrl = "",
                            IsInMenu = false,
                            IsPublished = false,
                            Title = "About"
                        },
                        new
                        {
                            Id = new Guid("06e20d97-8867-4d98-855c-be3c270573cb"),
                            Body = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque cursus erat non congue efficitur. Nulla sollicitudin sit amet dolor sed vestibulum. Aenean laoreet, nibh ac hendrerit egestas, metus urna semper orci, nec aliquet urna tellus at nibh. Vivamus vel sapien eget libero cursus hendrerit sed at quam. Etiam nec turpis urna. Donec at lacus in nibh cursus ullamcorper eget vitae lorem. In congue consectetur purus vitae porta. Donec volutpat rhoncus nisl, et placerat tellus fringilla et.",
                            Created = new DateTime(2021, 4, 2, 14, 23, 7, 273, DateTimeKind.Local).AddTicks(134),
                            ImageUrl = "",
                            IsInMenu = false,
                            IsPublished = false,
                            Title = "FAQ"
                        },
                        new
                        {
                            Id = new Guid("ec0c3ac3-8618-4e5e-a629-e0db55887c15"),
                            Body = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque cursus erat non congue efficitur. Nulla sollicitudin sit amet dolor sed vestibulum. Aenean laoreet, nibh ac hendrerit egestas, metus urna semper orci, nec aliquet urna tellus at nibh. Vivamus vel sapien eget libero cursus hendrerit sed at quam. Etiam nec turpis urna. Donec at lacus in nibh cursus ullamcorper eget vitae lorem. In congue consectetur purus vitae porta. Donec volutpat rhoncus nisl, et placerat tellus fringilla et.",
                            Created = new DateTime(2021, 4, 2, 14, 23, 7, 273, DateTimeKind.Local).AddTicks(196),
                            ImageUrl = "https://puppypetdog.com/wp-content/uploads/2019/11/contact-header-image.jpg",
                            IsInMenu = false,
                            IsPublished = false,
                            Title = "Contact"
                        });
                });

            modelBuilder.Entity("GameQuest.Data.MainCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MainCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0dd64c02-7aa0-467a-b71c-778cc082e514"),
                            Created = new DateTime(2021, 4, 2, 14, 23, 7, 270, DateTimeKind.Local).AddTicks(5339),
                            Description = "",
                            Name = "Nintendo"
                        },
                        new
                        {
                            Id = new Guid("4f6c9c44-d2bf-43af-a372-aff15e48ae28"),
                            Created = new DateTime(2021, 4, 2, 14, 23, 7, 272, DateTimeKind.Local).AddTicks(3417),
                            Description = "",
                            Name = "Playstation"
                        },
                        new
                        {
                            Id = new Guid("2dfd820a-4260-44ec-95c2-f87576a31294"),
                            Created = new DateTime(2021, 4, 2, 14, 23, 7, 272, DateTimeKind.Local).AddTicks(3446),
                            Description = "",
                            Name = "Xbox"
                        },
                        new
                        {
                            Id = new Guid("8046fd8e-2643-4f66-9a01-c95ad87fc75e"),
                            Created = new DateTime(2021, 4, 2, 14, 23, 7, 272, DateTimeKind.Local).AddTicks(3451),
                            Description = "",
                            Name = "PC"
                        });
                });

            modelBuilder.Entity("GameQuest.Data.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId1")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId1");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("GameQuest.Data.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deals")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Sale")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("75d2dbd2-fff9-474e-b4ea-84b6e8c58156"),
                            CategoryId = new Guid("951772f3-566d-402b-b100-af86c9d13c9d"),
                            Created = new DateTime(2021, 4, 2, 14, 23, 7, 273, DateTimeKind.Local).AddTicks(1030),
                            Deals = false,
                            Description = "Halo: Combat Evolved, simply known as Halo, is a first-person shooter video game developed by Bungie and published by Microsoft Game Studios. It was released as a launch title for Microsoft's Xbox video game console on November 15, 2001. Microsoft released versions of the game for Windows and Mac OS X in 2003.",
                            ImgUrl = "https://halo.wiki.gallery/images/6/6a/Halo_Combat_Evolved_cover.png",
                            IsVisible = false,
                            Name = "Halo: Combat Evolved",
                            Price = 599.0,
                            Sale = 0.0
                        },
                        new
                        {
                            Id = new Guid("7ae8c3bc-869c-4e6a-a262-a31c6e44aa8b"),
                            CategoryId = new Guid("dbb9b3fc-904a-4dad-857f-6fbb6e5b5048"),
                            Created = new DateTime(2021, 4, 2, 14, 23, 7, 273, DateTimeKind.Local).AddTicks(3688),
                            Deals = false,
                            Description = "Counter-Strike: Global Offensive is a multiplayer first-person shooter video game developed by Valve and Hidden Path Entertainment. It is the fourth game in the Counter-Strike series and was released for Windows, macOS, Xbox 360, and PlayStation 3 in August 2012, while the Linux version was released in 2014.",
                            ImgUrl = "https://static.wikia.nocookie.net/cswikia/images/1/1e/Csgo_steam_store_header_latest.jpg",
                            IsVisible = false,
                            Name = "Counter-Strike: Global Offensive",
                            Price = 49.0,
                            Sale = 0.0
                        },
                        new
                        {
                            Id = new Guid("7684ec6c-d95e-44e2-a369-f0e49ca17226"),
                            CategoryId = new Guid("951772f3-566d-402b-b100-af86c9d13c9d"),
                            Created = new DateTime(2021, 4, 2, 14, 23, 7, 273, DateTimeKind.Local).AddTicks(3728),
                            Deals = true,
                            Description = "Fable is a series of action role-playing video games for Xbox, Microsoft Windows, macOS, Xbox 360 and Xbox One platforms. The series was developed by Lionhead Studios until the studio was closed in 2016, and is published by Xbox Game Studios",
                            ImgUrl = "https://upload.wikimedia.org/wikipedia/en/5/5b/Fablebox.jpg",
                            IsVisible = false,
                            Name = "Fable",
                            Price = 599.0,
                            Sale = 0.0
                        },
                        new
                        {
                            Id = new Guid("41751510-5814-42eb-aa61-448dfa9e181e"),
                            CategoryId = new Guid("dbb9b3fc-904a-4dad-857f-6fbb6e5b5048"),
                            Created = new DateTime(2021, 4, 2, 14, 23, 7, 273, DateTimeKind.Local).AddTicks(3747),
                            Deals = true,
                            Description = "F1 2020 is the official video game of the 2020 Formula 1 and Formula 2 Championships developed and published by Codemasters.",
                            ImgUrl = "https://s3.gaming-cdn.com/images/products/7589/271x377/f1-2020-cover.jpg",
                            IsVisible = false,
                            Name = "F1 2020",
                            Price = 599.0,
                            Sale = 0.0
                        },
                        new
                        {
                            Id = new Guid("cfbb8570-6f05-42c2-86a1-eb61b520c75f"),
                            CategoryId = new Guid("df7cfae7-8317-49a8-8fda-b46b12e9ef6d"),
                            Created = new DateTime(2021, 4, 2, 14, 23, 7, 273, DateTimeKind.Local).AddTicks(3764),
                            Deals = true,
                            Description = "The Xbox controller is the primary game controller for Microsoft's Xbox home video game console and was introduced at the Game Developers Conference in 2000. ",
                            ImgUrl = "https://www.geeky-gadgets.com/wp-content/uploads/2018/08/Wireless-Controller-Grey-Blue-2.jpg",
                            IsVisible = false,
                            Name = "Xbox Controller",
                            Price = 599.0,
                            Sale = 0.0
                        });
                });

            modelBuilder.Entity("GameQuest.Data.SubCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SubCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e7bc4f99-8b04-4fdd-94b3-1ee74d0d4994"),
                            Created = new DateTime(2021, 4, 2, 14, 23, 7, 272, DateTimeKind.Local).AddTicks(4267),
                            Description = "",
                            Name = "Games"
                        },
                        new
                        {
                            Id = new Guid("217c83c9-1531-40e5-abc9-a20cc9edfcf0"),
                            Created = new DateTime(2021, 4, 2, 14, 23, 7, 272, DateTimeKind.Local).AddTicks(4966),
                            Description = "",
                            Name = "Accesories"
                        },
                        new
                        {
                            Id = new Guid("1d5ad12d-d31d-489c-95cd-cf3e016b782d"),
                            Created = new DateTime(2021, 4, 2, 14, 23, 7, 272, DateTimeKind.Local).AddTicks(4978),
                            Description = "",
                            Name = "Controllers"
                        },
                        new
                        {
                            Id = new Guid("f42ff7d6-7741-47cb-9471-671147f3bfc3"),
                            Created = new DateTime(2021, 4, 2, 14, 23, 7, 272, DateTimeKind.Local).AddTicks(4981),
                            Description = "",
                            Name = "Console"
                        });
                });

            modelBuilder.Entity("GameQuest.Data.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = "6f56c45b-17d7-4df3-bc35-8824cc426b60",
                            ConcurrencyStamp = "4e3efbbe-c881-4a6d-b576-cd8e723a9458",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "d44a7182-a47e-4e90-8c7c-d0deb5c07e9f",
                            ConcurrencyStamp = "6d91f287-28cb-4805-9aba-4e5815330cf3",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        },
                        new
                        {
                            Id = "6277828a-d24a-4b0f-8005-7bcfb7e6166a",
                            ConcurrencyStamp = "331d5fe8-2282-4b20-bf30-fc7edc3f5558",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("GameQuest.Data.Category", b =>
                {
                    b.HasOne("GameQuest.Data.MainCategory", "MainCategory")
                        .WithMany()
                        .HasForeignKey("MainCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameQuest.Data.SubCategory", "SubCategory")
                        .WithMany()
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MainCategory");

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("GameQuest.Data.Order", b =>
                {
                    b.HasOne("GameQuest.Data.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameQuest.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId1");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameQuest.Data.Product", b =>
                {
                    b.HasOne("GameQuest.Data.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("GameQuest.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("GameQuest.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameQuest.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("GameQuest.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
